- id: golangci-lint
  name: golangci-lint
  description: Fast linters runner for Go. Note that only modified files are linted, so linters like 'unused' that need to scan all files won't work as expected.
  entry: golangci-lint run --new-from-rev HEAD --fix
  types: [go]
  language: golang
  require_serial: true
  pass_filenames: false
- id: golangci-lint-full
  name: golangci-lint-full
  description: Fast linters runner for Go. Runs on all files in the repo. Use this hook if you use pre-commit in CI.
  entry: golangci-lint run -c ./.golangci.yml --fix
  types: [go]
  language: golang
  require_serial: true
  pass_filenames: false
